### ISSUE TITLE
Docker setup not working - "Pending migrations exist"

### ISSUE THREAD

**Issue by etfz** [frain-dev/convoy#1118]
Hello,

Trying to deploy Convoy using Docker Compose and the instructions found here:
https://getconvoy.io/docs/deploy/docker#installation-procedures

The web container fails with the following error:
```
FATAL migrate: Pending migrations exist, please run convoy migrate first
```

**Comment by jirevwe** [comment]
Hey @etfz,

You can this to get it to work

```sh
$ docker run --network=host -v `pwd`/convoy.json:/convoy.json docker.cloudsmith.io/convoy/convoy/frain-dev/convoy:latest migrate up

$ docker run --network=host -v `pwd`/convoy.json:/convoy.json docker.cloudsmith.io/convoy/convoy/frain-dev/convoy:latest
```

This is something we have noticed and we have updated the image on the main branch making it easier to run, we just have not released a new image yet. There's a known bug when running `convoy migrate up` which might make you have to run the command twice.

**Comment by jirevwe** [comment]
Hey @etfz,

You can this to get it to work.

```yaml
version: "3"

services:
  convoy_server:
    image: docker.cloudsmith.io/convoy/convoy/frain-dev/convoy:latest
    entrypoint: ["./cmd", "server", "--config", "convoy.json"]
    restart: on-failure
    volumes:
      - ./convoy.json:/convoy.json
    ports:
      - 5005:5005
    depends_on:
      - convoy_migrate
      - mongo
      - redis_server
    networks:
      - backendCluster

  convoy_migrate:
    image: docker.cloudsmith.io/convoy/convoy/frain-dev/convoy:latest
    entrypoint: ["./cmd", "migrate", "up", "--config", "convoy.json"]
    restart: on-failure
    volumes:
      - ./convoy.json:/convoy.json
    depends_on:
      - mongo
      - redis_server
    networks:
      - backendCluster

  scheduler:
    image: docker.cloudsmith.io/convoy/convoy/frain-dev/convoy:latest
    entrypoint: ["./cmd", "scheduler", "--config", "convoy.json"]
    volumes:
      - ./convoy.json:/convoy.json
    restart: on-failure
    depends_on:
      - convoy_migrate
      - mongo
      - redis_server
    networks:
      - backendCluster

  worker:
    image: docker.cloudsmith.io/convoy/convoy/frain-dev/convoy:latest
    entrypoint: ["./cmd", "worker", "--config", "convoy.json"]
    volumes:
      - ./convoy.json:/convoy.json
    restart: on-failure
    depends_on:
      - convoy_migrate
      - mongo
      - redis_server
    networks:
      - backendCluster

  mongo:
    image: mongo:latest
    hostname: mongo
    container_name: mongo
    restart: always
    volumes:
      - /var/convoy/data/mongo:/data/db
    networks:
      - backendCluster

  redis_server:
    image: redis:alpine
    hostname: redis_server
    container_name: redis_server
    restart: always
    networks:
      - backendCluster

networks:
  backendCluster:
```

This is something we have noticed and we have updated the image on the main branch making it easier to run, we just have not released a new image yet.
