### ISSUE TITLE
Not able send event

### ISSUE THREAD

**Issue by NanFengCheong** [frain-dev/convoy#1191]
Event doesnt send out.
Log: convoy_server_1
```
convoy_server_1  | time="2022-11-29T06:39:47Z" level=error msg="realm file_realm failed to authenticate cred: " error="unsupported credential type: JWT"
convoy_server_1  | time="2022-11-29T06:39:47Z" level=error msg="realm native_realm failed to authenticate cred: " error="native_realm only authenticates credential type BEARER"
```

convoy.json
```
{
  "environment": "development",
  "host": "http://localhost:5005",
  "database": {
    "type": "mongodb",
    "dsn": "mongodb://mongo:27017/convoy?readPreference=primary&ssl=false"
  },
  "queue": {
    "type": "redis",
    "redis": {
      "dsn": "redis://redis_server:6379"
    }
  },
  "cache": {
    "type": "redis",
    "redis": {
      "dsn": "redis://redis_server:6379"
    }
  },
  "server": {
    "http": {
      "port": 5005,
      "worker_port": 5006
    }
  },
  "disable_endpoint": false,
  "auth": {
    "native": {
      "enabled": false
    },
    "jwt": {
      "enabled": true
    }
  }
}
```

docker-compose.yml
```
version: "3"

services:
  convoy_server:
    image: docker.cloudsmith.io/convoy/convoy/frain-dev/convoy:latest
    entrypoint: ["./cmd", "server", "--config", "convoy.json"]
    restart: on-failure
    volumes:
      - ./convoy.json:/convoy.json
    ports:
      - 5005:5005

    depends_on:
      - convoy_migrate
      - mongo
      - redis_server
    networks:
      - backendCluster

  convoy_migrate:
    image: docker.cloudsmith.io/convoy/convoy/frain-dev/convoy:latest
    entrypoint: ["./cmd", "migrate", "up", "--config", "convoy.json"]
    restart: on-failure
    volumes:
      - ./convoy.json:/convoy.json
    depends_on:
      - mongo
      - redis_server
    networks:
      - backendCluster

  scheduler:
    image: docker.cloudsmith.io/convoy/convoy/frain-dev/convoy:latest
    entrypoint: ["./cmd", "scheduler", "--config", "convoy.json"]
    volumes:
      - ./convoy.json:/convoy.json

    restart: on-failure
    depends_on:
      - convoy_migrate
      - mongo
      - redis_server
    networks:
      - backendCluster

  worker:
    image: docker.cloudsmith.io/convoy/convoy/frain-dev/convoy:latest
    entrypoint: ["./cmd", "worker", "--config", "convoy.json"]
    volumes:
      - ./convoy.json:/convoy.json

    restart: on-failure
    depends_on:
      - convoy_migrate
      - mongo
      - redis_server
    networks:
      - backendCluster

  mongo:
    image: mongo:latest
    hostname: mongo
    container_name: mongo
    restart: always
    volumes:
      - /var/convoy/data/mongo:/data/db
    networks:
      - backendCluster

  redis_server:
    image: redis:alpine
    hostname: redis_server
    container_name: redis_server
    restart: always
    networks:
      - backendCluster

networks:
  backendCluster:

```
