### ISSUE TITLE
[Bug report]: unknown command "scheduler" for "Convoy"

### ISSUE THREAD

**Issue by vaisov-gemba** [frain-dev/convoy#2252]
### Describe the bug
Scheduler container is constantly restarting with error:
```
Error: unknown command "scheduler" for "Convoy"
Run 'Convoy --help' for usage.
time="2025-03-03T09:48:38Z" level=fatal msg="unknown command \"scheduler\" for \"Convoy\""
```

### To Reproduce
1. Deploy Convoy based on https://www.getconvoy.io/docs/deployment/install-convoy/docker (same error both for `latest` and `v25.2.1` versions)
2. Check logs of scheduler container

My `docker-compose.yml` scheduler part:
```
    scheduler:
        image: getconvoy/convoy:v25.2.1
        command: ["./cmd", "scheduler", "--config", "convoy.json"]
        volumes:
            - ./convoy.json:/convoy.json
        restart: unless-stopped
        depends_on:
            web:
                condition: service_healthy
```

### Expected behavior
No errors in scheduler container logs

### Stack (please complete the following information):
 - Convoy: [v25.2.1]
 - PostgreSQL: [15.2-alpine]
 - Redis: [7-alpine]
 - OS: [Ubuntu 24.04 LTS]
