### ISSUE TITLE
[Bug report]: Prometheus metrics not exposed on /metrics endpoint

### ISSUE THREAD

**Issue by TokuiNico** [frain-dev/convoy#2289]
### Describe the bug
After enabling Prometheus metrics via the recommended environment variables (`CONVOY_ENABLE_FEATURE_FLAG=prometheus` and `CONVOY_METRICS_BACKEND=prometheus`), the `/metrics` endpoint returns nothing when accessing `http://localhost:5005/metrics`.

### To Reproduce
1. Follow the guide at https://www.getconvoy.io/docs/deployment/install-convoy/docker#deploy-locally to start Convoy with Docker Compose.
2. Add the following environment variables to the `web` service:
   - `CONVOY_ENABLE_FEATURE_FLAG=prometheus`
   - `CONVOY_METRICS_BACKEND=prometheus`
3. Start the services using `docker compose up`.
4. Access `http://localhost:5005/metrics`.

### Expected behavior
The `/metrics` endpoint should return valid Prometheus metrics.

### Screenshots
N/A

### Stack (please complete the following information):
 - Convoy: v25.2.1
 - PostgreSQL: 15.2-alpine
 - Redis: 7-alpine
 - OS: macOS 14.4.1 (Apple Silicon, running Docker Desktop)
 - Browser: N/A (accessing via `curl`/browser)

### Additional context
Here is my `docker-compose.yml` for reference:

```yaml
services:
  web:
    image: getconvoy/convoy:latest
    command: ["/start.sh"]
    volumes:
      - ./convoy.json:/convoy.json
    restart: unless-stopped
    ports:
      - "5005:5005"
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider localhost:5005/health"]
      interval: 5s
      timeout: 15s
      retries: 3
      start_period: 5s
    depends_on:
      - postgres
      - redis_server
      - pgbouncer
    environment:
      CONVOY_ENABLE_FEATURE_FLAG: prometheus
      CONVOY_METRICS_BACKEND: prometheus

  agent:
    image: getconvoy/convoy:latest
    command: ["./cmd", "agent", "--config", "convoy.json"]
    ports:
      - "5008:5008"
    volumes:
      - ./convoy.json:/convoy.json
    restart: unless-stopped
    depends_on:
      web:
        condition: service_healthy

  pgbouncer:
    image: bitnami/pgbouncer:latest
    hostname: pgbouncer
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - ./conf/.env
    volumes:
      - ./conf/:/bitnami/pgbouncer/conf/
      - ./conf/userlists.txt:/bitnami/userlists.txt
    ports:
      - "6432:6432"

  postgres:
    image: postgres:15.2-alpine
    restart: on-failure
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: convoy
      POSTGRES_USER: convoy
      POSTGRES_PASSWORD: pg_password
      PGDATA: /data/postgres
    volumes:
      - postgresql_master_data:/data/postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U convoy"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  redis_server:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data

volumes:
  postgresql_master_data:
  redis_data:
```
Let me know if there’s any additional config or step I may be missing.
